### ISSUE TITLE
Make the nexus command generic?

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/normansinitic#5]
The current nexus code snippet converts the structural data to a nexus file. I added code to generate the nexus from the lexical data (need to adjust one problem, but othertwise it should be fine). 

I guess, for now, leaving a python script inside a dataset is probably good for testing and illustrating how data can be used, but in general, I think it may be time to think of how to make scripts that come in on top more unified. So for starters: should the script be in a specific folder? Can we register commands along with the script, via the setup.py?

For cldfbench pure illustration, we won't need this, but I thought: once we have all these possibilities...

**Comment by LinguList** [comment]
Structural data:

![Screenshot_2019-11-22_16-02-17](https://user-images.githubusercontent.com/2916210/69436355-86926d80-0d41-11ea-8303-6c6072bf8952.png)

**Comment by LinguList** [comment]
Lexical data: 

![Screenshot_2019-11-22_16-02-39](https://user-images.githubusercontent.com/2916210/69436385-90b46c00-0d41-11ea-8c4f-f57c7a7f8a50.png)

**Comment by LinguList** [comment]
I think this is nice for the presentation.

**Comment by xrotwang** [comment]
We should provide this functionality as subcommands registered to be run with `cldfbench`.
